name: Notify Slack on deploy

on:
  workflow_call:
    inputs:
      result:
        description: Result of the deploy. 'success' is happy; anything else is sad
        required: true
        type: string
      commit_sha:
        description: SHA for the deployed Git commit
        required: true
        type: string
    secrets:
      slack_webhook:
        required: true

jobs:
    slack:
      runs-on: ubuntu-latest

      steps:
        - name: set up happy status
          if: ${{ inputs.result == 'success' }}
          run: |
            echo "status_emoji=yey" >> $GITHUB_ENV
            echo "status_color=06B594" >> $GITHUB_ENV

        - name: set up sad status
          if: ${{ inputs.result != 'success' }}
          run: |
            echo "status_emoji=poop" >> $GITHUB_ENV
            echo "status_color=EA7363" >> $GITHUB_ENV

        - name: shorten the commit hash
          run: |
            sha=${{ inputs.commit_sha }}
            echo "short_commit=${sha:0:16}" >> $GITHUB_ENV

        - name: send the deploy result to slack
          continue-on-error: true
          env:
            slack_webhook: ${{ secrets.slack_webhook }}
            link: https://github.com/${{ github.repository }}
          run: |
            curl ${{ env.slack_webhook }} \
              --request POST \
              --header 'Content-type: application/json' \
              --data '{
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Deploy: ${{ github.repository }}"
                    }
                  },
                  {
                    "type": "divider"
                  }
                ],
                "attachments": [
                  {
                    "color": "#${{ env.status_color }}",
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Status*\n:${{ env.status_emoji }}: <${{ env.link }}/actions/runs/${{ github.run_id }}|${{ inputs.result }}>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Environment*\n${{ github.event.inputs.environment }}"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Branch/tag*\n<${{ env.link }}/tree/${{ github.ref_name }}|`${{ github.ref_name }}`>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Commit*\n<${{ env.link }}/commits/${{ inputs.commit_sha }}|`${{ env.short_commit }}`>"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Initiated by*\n@${{ github.event.inputs.actor || 'GitHub' }}"
                          }
                        ]
                      }
                    ]
                  }
                ]
            }'
